### ISSUE TITLE
Error running problem1_template.py

### ISSUE THREAD

**Issue by ayushgupt** [Auquan/quant-quest-3#1]
getting this KeyError

```
Loading your config dicts and prediction function
Loaded config dicts and prediction function, Loading Problem 1 Params
Loaded Problem 1 Params, Loading Backtester and Data
Processing data for stock: ABC
Processing data for stock: DEF
Loaded Backtester and Data Loaded, Backtesting
2010-06-02 09:20:00
Traceback (most recent call last):
  File "problem1_template.py", line 288, in <module>
    tradingSystem.startTrading(onlyAnalyze=False, shouldPlot=True, makeInstrumentCsvs=True)
  File "/usr/local/lib/python3.6/dist-packages/backtester/trading_system.py", line 174, in startTrading
    self.updateFeaturesAndExecute(currentTimeUpdate, isClose, onlyAnalyze)
  File "/usr/local/lib/python3.6/dist-packages/backtester/trading_system.py", line 85, in updateFeaturesAndExecute
    self.updateFeatures(timeOfUpdate)
  File "/usr/local/lib/python3.6/dist-packages/backtester/trading_system.py", line 109, in updateFeatures
    self.instrumentManager.updateFeatures(timeOfUpdate)
  File "/usr/local/lib/python3.6/dist-packages/backtester/instruments_manager.py", line 237, in updateFeatures
    self.updateInstrumentFeatures(timeOfUpdate)
  File "/usr/local/lib/python3.6/dist-packages/backtester/instruments_manager.py", line 229, in updateInstrumentFeatures
    instrumentManager=self)
  File "/usr/local/lib/python3.6/dist-packages/backtester/features/momentum_feature.py", line 13, in computeForInstrument
    dataDf = instrumentLookbackData.getFeatureDf(featureParams['featureName'])
  File "/usr/local/lib/python3.6/dist-packages/backtester/instruments_lookback_data.py", line 24, in getFeatureDf
    return self.__data[featureKey].getData()
KeyError: 'ADJCLOSE'
```

**Comment by chandinijain** [comment]
Apologies, this is now been fixed. Please re-download the folder and try again.
